# 2.3 Lab: Introduction to R

## 2.3.1 Basic Commands

In [1]:
# assign and show a vector
x <- c(1,3,2,5)
x

[1] 1 3 2 5

In [2]:
# re-assign a new vector to the variable x and show
x = c(1,6,2)
x

[1] 1 6 2

In [3]:
# assign a vector without showing
y = c(1,4,3)

In [4]:
# pull up the help for the length function
?length

In [5]:
# check the length of x
length(x)

[1] 3

In [6]:
# check the length of y
length(y)

[1] 3

In [7]:
# add the vectors x and y and show without saving
x + y

[1]  2 10  5

In [8]:
?ls

In [9]:
# show all objects in the base namespace
ls()

[1] "x" "y"

In [10]:
# remove objects x and y and check that they are gone
rm(x,y)
ls()

character(0)

In [11]:
# re-declare x and y and show all objects
x = 1
y = 2
ls()

[1] "x" "y"

In [12]:
# remove all objects
rm(list=ls())
ls()

character(0)

In [13]:
# pull up the help for the matrix function
?matrix

In [14]:
# create a matrix
x = matrix(data=c(1,2,3,4), ncol=2, nrow=2)
x

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [15]:
# note, nrow argument is not necessary
x = matrix(data=c(1,2,3,4), ncol=2, nrow=2)
x

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [16]:
# passing arguments in order has instead of by keyword has same result
x = matrix(c(1,2,3,4), 2, 2)
x

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [17]:
# by default, matrices are filled form the vector by column
# to change this specify byrow=TRUE
matrix(c(1,2,3,4), 2, 2, byrow=TRUE)

[,1] [,2]
[1,] 1    2   
[2,] 3    4

In [18]:
# take the elementwise square root of x
sqrt(x)

[,1]     [,2]    
[1,] 1.000000 1.732051
[2,] 1.414214 2.000000

In [19]:
# take elementwise square of x
x ^ 2

[,1] [,2]
[1,] 1     9  
[2,] 4    16

In [20]:
?rnorm

In [21]:
# create a vector of 50 standard normal draws
x = rnorm(50)

# create another vector by adding N(mean=50, standard deviation=.1) to x
y = x + rnorm(50, mean=50, sd=.1)

# check the covariance between the vectors
cov(x, y)

[1] 1.090797

In [22]:
# do it again
x = rnorm(50)
y = x + rnorm(50, mean=50, sd=.1)
cov(x, y)

[1] 0.8561505

In [23]:
# do it again setting the seed
set.seed(1303)
x = rnorm(50)
y = x + rnorm(50, mean=50, sd=.1)
cov(x, y)

[1] 0.7961235

In [24]:
# do it yet again setting the seed
set.seed(1303)
x = rnorm(50)
y = x + rnorm(50, mean=50, sd=.1)
cov(x, y)

[1] 0.7961235

In [25]:
# set the seed and generate 50 standard normal draws
set.seed(1303)
rnorm(50)

[1] -1.1439763145  1.3421293656  2.1853904757  0.5363925179  0.0631929665
 [6]  0.5022344825 -0.0004167247  0.5658198405 -0.5725226890 -1.1102250073
[11] -0.0486871234 -0.6956562176  0.8289174803  0.2066528551 -0.2356745091
[16] -0.5563104914 -0.3647543571  0.8623550343 -0.6307715354  0.3136021252
[21] -0.9314953177  0.8238676185  0.5233707021  0.7069214120  0.4202043256
[26] -0.2690521547 -1.5103172999 -0.6902124766 -0.1434719524 -1.0135274099
[31]  1.5732737361  0.0127465055  0.8726470499  0.4220661905 -0.0188157917
[36]  2.6157489689 -0.6931401748 -0.2663217810 -0.7206364412  1.3677342065
[41]  0.2640073322  0.6321868074 -1.3306509858  0.0268888182  1.0406363208
[46]  1.3120237985 -0.0300020767 -0.2500257125  0.0234144857  1.6598706557

In [26]:
# without re-setting the seed generate 50 more standard normal draws
rnorm(50)

[1]  1.00185188  0.26300143 -0.02835910 -0.55625904 -0.11956114 -1.03629594
 [7] -0.65663801  0.53071490  0.11239650 -2.07756129  0.42047788  0.34127692
[13] -1.11146959  0.84377453 -0.85525778  2.24788116 -1.37211474  0.93599500
[19]  0.54973757  0.51758744 -0.56054669 -0.63876770 -0.06500831  0.37530956
[25]  1.30692614 -0.61058086  0.32282993  1.75126495  1.55928971  0.64713105
[31] -1.93202340 -0.96938200  1.00148882  0.15220012 -0.04515586 -0.50296757
[37] -0.25911284  1.01738122 -1.72582568  0.93284077  0.02782077  1.58725296
[43]  0.23574669 -0.21068373 -0.16983068  0.76280099  0.43017948  1.37181976
[49]  1.57143594  0.13737399

In [27]:
# set the seed
set.seed(3)

# create a vector of 100 standard normal draws
y = rnorm(100)

# calculate the mean
mean(y)

# calculate the variance
var(y)

# calculate the standard deviation two ways
sqrt(var(y))
sd(y)

[1] 0.01103557

[1] 0.7328675

[1] 0.8560768

[1] 0.8560768